sql_admin_password   = "YourProductionPassword123!"
github_account_name  = "waigisteve"
github_repo_name     = "azure-data-pipeline"
github_branch        = "main"
databricks_token     = "dapiXXXXXXXXXXXXXXXX"
